# Generated by Django 5.1.2 on 2024-11-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerGenderSummary",
            fields=[],
            options={
                "verbose_name": "model.customer-gender-summary.name",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("customer.customer",),
        ),
    ]
