# Generated by Django 5.0.3 on 2024-05-22 17:22

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("language", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="model.field.id",
                    ),
                ),
                (
                    "tag",
                    models.SlugField(max_length=255, verbose_name="model.field.tag"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="model.field.title"),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="model.field.content"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="model.field.active"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="language.language",
                        verbose_name="model.field.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "model.content.name",
                "verbose_name_plural": "model.content.name.plural",
                "db_table": "content",
                "indexes": [
                    models.Index(fields=["language"], name="content_language"),
                    models.Index(fields=["tag"], name="content_tag"),
                    models.Index(fields=["title"], name="content_title"),
                ],
            },
        ),
    ]
