# Generated by Django 5.0.3 on 2024-05-22 17:55

import django_autoslugfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="tag",
            field=django_autoslugfield.fields.AutoSlugField(
                in_respect_to="title",
                max_length=255,
                reserve_chars="model.field.tag",
                title_field=None,
                unique=True,
            ),
        ),
    ]
