# Generated by Django 5.0.3 on 2024-05-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_content_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="tag",
            field=models.SlugField(
                blank=True,
                default=None,
                help_text="model.field.tag.help",
                max_length=255,
                null=True,
                verbose_name="model.field.tag",
            ),
        ),
    ]
