# Generated by Django 5.0.3 on 2024-04-27 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="model.field.id",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=255, verbose_name="model.field.external-id"
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        max_length=255, verbose_name="model.field.gateway"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="model.field.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "model.subscription.name",
                "verbose_name_plural": "model.subscription.name.plural",
                "db_table": "subscription",
                "indexes": [
                    models.Index(
                        fields=["external_id"], name="subscription_external_id"
                    ),
                    models.Index(fields=["gateway"], name="subscription_gateway"),
                ],
            },
        ),
    ]
