# Generated by Django 6.0.7 on 2026-07-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="event_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="model.field.event-id",
            ),
        ),
    ]
