# Generated by Django 5.2 on 2025-05-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="model.field.email"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="model.field.created-at"
                    ),
                ),
            ],
            options={
                "verbose_name": "model.newsletter-entry.name",
                "verbose_name_plural": "model.newsletter-entry.name.plural",
                "db_table": "newsletter_entry",
                "indexes": [
                    models.Index(fields=["email"], name="newsletter_entry_email"),
                    models.Index(
                        fields=["created_at"], name="newsletter_entry_created_at"
                    ),
                ],
            },
        ),
    ]
