# Generated by Django 5.0.3 on 2024-05-16 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="model.field.user",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["language"], name="customer_language"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["mobile_phone"], name="customer_mobile_phone"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["home_phone"], name="customer_home_phone"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["gender"], name="customer_gender"),
        ),
    ]
