# Generated by Django 5.0.3 on 2024-05-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="model.field.id",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=255, verbose_name="model.field.external-id"
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        max_length=255, verbose_name="model.field.gateway"
                    ),
                ),
            ],
            options={
                "verbose_name": "model.subscription.name",
                "verbose_name_plural": "model.subscription.name.plural",
                "db_table": "subscription",
            },
        ),
    ]
