# Generated by Django 5.0.3 on 2024-05-16 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="model.field.user",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["external_id"], name="subscription_external_id"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["gateway"], name="subscription_gateway"),
        ),
    ]
